AppName = "APP By Gongna"
LogLevel = "DEBUG"

[mysql]
  database = "Test"
  ip = "127.0.0.1"
  password = "123456"
  port = 3306
  user = "gongna2"

[redis]
  ip = "127.0.0.1"
  port = 4344

[token]
  expired: 30 # 过期时间 30 天
  
